### PR TITLE
Add a cmake buildsystem to kdreports

### PR DESCRIPTION
**Pull request by sengels**
This is based on the buildsystem of kdsoap.

### CODE REVIEW

**Comment by dfaure-kdab** [comment]
Cool. This needs 1) testing on linux, 2) comparing the file list of the install dir between the qmake and cmake build systems.

@winterz, I think you like this kind of stuff? :-)

**Comment by winterz** [comment]
Yes, I'll take a look

**Comment by winterz** [comment]
first test fails:
$ cmake -DKDReports_ENFORCE_QT4_BUILD=True ..
-- Building KDReports 1.6.0 in Debug mode. Installing to /usr/local
CMake Error at CMakeLists.txt:113 (add_subdirectory):
  add_subdirectory given source "include" which is not an existing directory.

-- Could NOT find KDChart (missing:  KDChart_LIBRARIES KDChart_INCLUDE_DIR) 
-- Configuring incomplete, errors occurred!

**Comment by winterz** [comment]
the other day in KDSoap I added ECMGenerateHeader support to create the camelcase headers. I think we need to do the same here.

**Comment by sengels** [comment]
ok, I updated the patch, and took over the file from KDSoap.

**Comment by winterz** [comment]
looking good
problems:
* libkdreports.so*  should be installed under lib64, not lib
* the cmake buildsystem installs LICENSE.GPL.txt under shared/doc/KDReports, but the autogen buildsystem installs LICENSE.LGPL.txt instead.  I think both LICENSE.GPL.txt *and* LICENSE.LGPL.txt should be installed by both buildsystems.
* the convenience header KDReports in the cmake build is missing "include KDReports.h"

**Comment by winterz** [comment]
I fixed the autogen buildsystem so it now installs both LICENSE.GPL.txt and LICENSE.LGPL.txt

**Comment by sengels** [comment]
Hm, install location is exactly the same as on kdsoap?!? I also cannot reproduce that on windows, so maybe you or dfaure can check where the error is?

**Comment by winterz** [comment]
so close. we only need to fix the .so library install now. please try this patch on windows.
diff --git a/examples/tools/CMakeLists.txt b/examples/tools/CMakeLists.txt
index 4bdfa9d..897ad8d 100644
--- a/examples/tools/CMakeLists.txt
+++ b/examples/tools/CMakeLists.txt
@@ -11,4 +11,4 @@ set(SOURCES
 
 add_library(kdreporttesttools ${KDReports_LIBRARY_MODE} ${SOURCES})
 target_link_libraries(kdreporttesttools ${QT_LIBRARIES})
-set_target_properties(kdreporttesttools PROPERTIES DEFINE_SYMBOL KDREPORT_BUILD_TESTTOOLS_LIB)
+set_target_properties(kdreporttesttools PROPERTIES VERSION ${${PROJECT_NAME}_VERSION})
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index b2f9c1b..540e9fc 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -135,7 +135,8 @@ set(SOURCES
 
 add_library(kdreports ${KDReports_LIBRARY_MODE} ${SOURCES} ${KDREPORTS_UI} ${KDREPORTS_RES})
 target_link_libraries(kdreports ${QT_LIBRARIES})
-set_target_properties(kdreports PROPERTIES DEFINE_SYMBOL  KDREPORTS_BUILD_KDREPORTS_LIB)
+set_target_properties(kdreports PROPERTIES VERSION ${${PROJECT_NAME}_VERSION})
+
 install(TARGETS kdreports EXPORT KDReportsTargets
 RUNTIME DESTINATION ${INSTALL_RUNTIME_DIR}
 LIBRARY DESTINATION ${INSTALL_LIBRARY_DIR}

**Pull request merged**
