### PR TITLE
Mostly small issues found by Krazy

### PR DESCRIPTION
**Pull request by winterz**

### CODE REVIEW

**Comment by dfaure-kdab** [comment]
Hmm I'm not sure how to comment on the overall diff without having to find which individual commit introduces what...

There's a merge error with the recode fixes, in examples/Letter/Letter.cpp
+                << "Klarälvdalens Datakonsult AB\n"
                 << QString::fromUtf8("Klarälvdalens Datakonsult AB\n")
The added line shouldn't be there.

**Comment by dfaure-kdab** [comment]
Everything else looks good, thanks :-)

**Comment by winterz** [comment]
thanks for reviewing. will close this and create individual pull requests, 1 per commit.

**Comment by dfaure-kdab** [comment]
Urgh, I didn't want to give you that much more work. You can just fix the issues I mentionned above and we can merge the whole thing in one go. I was just confused about the merge error, but obviously it must be in one of the merge commits, doh.

**Pull request closed without merging**
